name: Deploy to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.1.7

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_ROLE_NAME }}
        aws-region: us-east-1

    - name: Upload to S3
      run: |
        aws s3 cp $PWD s3://${{ secrets.AWS_BUCKET_NAME }}/ --recursive --exclude "*" --include "*.html" --include "*.jpg"
